spring:
  application:
    name: inventory-service

  flyway:
    url: jdbc:postgresql://inventorydb.c4b4ogqqybf1.us-east-1.rds.amazonaws.com:5432/inventorydb
    user: postgres
    password: LONque123*
    baseline-on-migrate: true
    locations: classpath:db/migration


  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin


  main:
    web-application-type: reactive
  jackson:
    serialization:
      indent-output: true

postgresql:
  host: inventorydb.c4b4ogqqybf1.us-east-1.rds.amazonaws.com
  port: 5432
  database: inventorydb
  schema: public
  username: postgres
  password: LONque123*
  ssl: allow

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    org.flywaydb.core: DEBUG

security:
  jwt:
    secret: "LONque1234567890LONque1234567890abcd"
